### ISSUE TITLE
Develop wallet section on Hashed portal

### ISSUE THREAD

**Issue by jmgayosso** [hashed-io/hashed-network-portal-ui#100]
Develop de following specs

- [x] Create a new section in the menu for wallet
- [x] Develop a new page using vue 3 and composable
- [x] Develop a function to parse logged address and parse to ss58 and match with API data
- [x] Develop functions to get calcs
- [x] Implement pie chart in real time

**Comment by mgravitt** [comment]
- [x] Add address to page, using the ss58 prefix 9072 so that each address shows with a prefix of `ha`
- [x] Add address URL so site shows at https://hashed.club (@3yekn to update A record)

**Comment by mgravitt** [comment]
- [x] Users should be able to search for other contributors by address.. this can be an additional page or a link on the left menu that opens the existing page that lists all of the contributors

**Comment by mgravitt** [comment]
- [x] I like how it is live :100: Can we add a timer that shows "Estimated time to fully vest" which could just be a formula of Remaining to vest / HASH per block * 12 s.  Perhaps show it as a countdown clock (?)
- [x] Which charting package are you using for the pie chart? Is there a horizontal progress bar option?  
- [ ] What other metrics do we have available? If there is a horizontal progress bar for vesting, maybe we can put a summary box on the upper right? 
![image](https://user-images.githubusercontent.com/32852271/223418272-f509a569-3764-4e16-838b-9b75d717242e.png)

**Comment by mgravitt** [comment]
The minimum requirements for this release are: 
- [x] point hashed.club to this page
- [x] show address in `ha` format, either just to the right 'Wallet' or another header field
- [x] Change NBV on the menu to "Bitcoin Vaults" and add a warning box
- [x] Do not allow access unless user has HASH tokens - when a user click's Login, if they do not have HASH, error should read: "Permission denied. Your account must have HASH tokens to gain access."  and keep the user on the Login screen.

The other comments can be put into the next release unless they are very quick. I want us to get this out. @tlacloc @sebastianmontero is there any need for a `vest` button to call the `vest` extrinsic? 

Warning box on this page similar to this: 
![image](https://user-images.githubusercontent.com/32852271/223419465-fef2106f-92dc-4dee-81f5-f1f069f46ac2.png)

**Comment by mgravitt** [comment]
- [x] Remove in active buttons below language selector 
![image](https://user-images.githubusercontent.com/32852271/223422845-12fbffed-8b6e-4591-a8c9-d21437dc5044.png)

**Comment by jmgayosso** [comment]
> * [ ]  Add address to page, using the ss58 prefix 9072 so that each address shows with a prefix of `ha`
> * [ ]  Add address URL so site shows at https://hashed.club (@3yekn to update A record)

For the first point, You mean like "/wallet/5GNYTRTYASDT..." right? we can do it, but this link does not make sense since we need login on the portal to access to wallet page.

**Comment by jmgayosso** [comment]
> * [ ]  I like how it is live 💯 Can we add a timer that shows "Estimated time to fully vest" which could just be a formula of Remaining to vest / HASH per block * 12 s.  Perhaps show it as a countdown clock (?)
> * [ ]  Which charting package are you using for the pie chart? Is there a horizontal progress bar option?
> * [ ]  What other metrics do we have available? If there is a horizontal progress bar for vesting, maybe we can put a summary box on the upper right?
>   ![image](https://user-images.githubusercontent.com/32852271/223418272-f509a569-3764-4e16-838b-9b75d717242e.png)

I'm using chart.js with vue-chart-3 so we have a lot of chart types available, I will take a look and get a new proposal for chart

**Comment by mgravitt** [comment]
> 

No, I mean like this, just showing it on the page somewhere 

![image](https://user-images.githubusercontent.com/32852271/223454585-2ed0854d-0e74-4e78-bd99-9fe536748993.png)

**Comment by jmgayosso** [comment]
> 

Do you have an example for the first point? Where can I see my address on that format?
