### ISSUE TITLE
Develop participants page on portal

### ISSUE THREAD

**Issue by jmgayosso** [hashed-io/hashed-network-portal-ui#96]

**Comment by mgravitt** [comment]
Crowdloan participants should be able to view their contribution and vesting status on the portal, and also all participants data should be available for search.

When a user logs in by using an identity check via polkadot.js, they should see their data for: 
- contribution
- total reward
- reward remaining
- do they need ability to claim it? 

This should be a nicely designed 'wallet' or 'dashboard' style view. 

If and when possible, the user would have the ability to join the Hashed Network nostr relay for communications.
